export const PAGES = ["Home", "About", "Events", "Sub-Units", "Awards"];

export const TEAM = [
  { name: "Aya Jouni",         role: "Chair",                          photo: "/photos/Aya.png",      fb: "#", insta: "#", ln: "#" },
  { name: "Younes Abid",       role: "Vice Chair",                     photo: "/photos/Younes.png",   fb: "#", insta: "#", ln: "#" },
  { name: "Nadia Chechia",     role: "Secretary",                      photo: "/photos/Nadia.png",    fb: "#", insta: "#", ln: "#" },
  { name: "Amal Tounsi",       role: "Treasurer",                      photo: "/photos/Amal.png",     fb: "#", insta: "#", ln: "#" },
  { name: "Azza Hamdi",        role: "Webmaster",                      photo: "/photos/Azza.png",     fb: "#", insta: "#", ln: "#" },
  { name: "Salsabil Fatnsazy", role: "Membership Development Manager", photo: "/photos/Salsabil.png", fb: "#", insta: "#", ln: "#" },
  { name: "Med Taib Jomaa",    role: "Project Manager",                photo: "/photos/Taieb.png",    fb: "#", insta: "#", ln: "#" },
];

export const FORMER_MESSAGES = [
  {
    name: "Ayoub Abidi",
    role: "Treasurer 2024 · Vice Chair 2025",
    side: "left",
    color: "#00c48c",
    msg: `From managing budgets to shaping strategy, my years with IEEE ENIT SB were a masterclass in responsibility and teamwork. The branch gave me skills no classroom could resilience, adaptability, and the art of building something meaningful with a team. To the 2025 executive committee: you stand on strong shoulders. Make us proud.`,
  },
  {
    name: "Yosr Jabloun",
    role: "Chair 2025",
    side: "left",
    color: "#FFD700",
    msg: `Leading IEEE ENIT SB has been an honour beyond words. To every member who gave their time, energy and passion you are the soul of this branch. We did not just organise events; we built a community that uplifts, challenges and inspires. As we celebrate 20 years of legacy, I am proud to have been part of this story, and I am certain the best chapters are still ahead.`,
  },
  {
    name: "Yassine Soussi",
    role: "Chair 2024 – 2025",
    side: "right",
    color: "#00bfff",
    msg: `IEEE ENIT SB taught me what real leadership looks like it is not about titles, it is about service. Every workshop, every competition, every late night preparing an event was worth it because of the people around me. This branch has been a launchpad for engineers, innovators and leaders. Keep the flame alive, keep pushing boundaries, and keep shining together.`,
  },
];

export const EVS = [
  {
    name: "IEEEXtreme 19.0, Code Wars",
    photo: "/events/xtream.png",
    date: "Oct 19, 2025",
    loc: "ENIT, Tunis",
    cat: "CS Chapter",
    col: "#f5c400",
    desc: "A global 24-hour coding marathon in collaboration with IEEE ISTIC and IEEE EPT. Teams tackled algorithmic challenges, showcasing problem-solving and teamwork on an international stage.",
    url: "#",
  },
  {
    name: "Pink October, Rise for Hope",
    photo: "/events/pink.png",
    date: "October 2025",
    loc: "ENIT Campus",
    cat: "WIE Group",
    col: "#d63a8a",
    desc: "Breast cancer awareness day by IEEE WIE ENIT with Club Génie Civil and Club 3Zero. Featured screening sessions, expert health panels, and community engagement activities.",
    url: "#",
  },
  {
    name: "IEEE Day Celebration",
    photo: "/events/ieeeday.png",
    date: "Oct 1, 2025",
    loc: "ENIT & Online",
    cat: "IEEE Day",
    col: "#00bfff",
    desc: "Multi-event celebration: RoboticsCamp, C++ and Digital Twins workshops, blood donation, SDG campaigns, in collaboration with ESPRIT and FSS Student Branches.",
    url: "#",
  },
  {
    name: "WIE ACT 4.0",
    photo: "/events/wieact.png",
    date: "2025",
    loc: "Tunisia",
    cat: "WIE Group",
    col: "#d63a8a",
    desc: "Annual Congress of Tunisia under the theme Agri-WIE: Empowering Women in the Green Revolution. Over 370 participants from 37 WIE groups joined workshops, mentorship roundtables, and innovation pitches.",
    url: "#",
  },
  {
    name: "IEEE LUMEN 1.0",
    photo: "/events/lumen.png",
    date: "2025",
    loc: "ENIT, Tunis",
    cat: "CS Chapter",
    col: "#f5c400",
    desc: "A career-focused event exploring IT pathways through expert panels on AI, IoT, Cybersecurity, and Software Engineering, followed by hands-on workshops in each domain.",
    url: "#",
  },
  {
    name: "1st General Assembly",
    photo: "/events/ag.png",
    date: "2025",
    loc: "ENIT, Tunis",
    cat: "Student Branch",
    col: "#005f99",
    desc: "IEEE ENIT SB's General Assembly presented yearly achievements, introduced the new Executive Committee, and outlined chapter plans. Around 200 members attended, with alumni insights and recognition segments.",
    url: "#",
  },
  {
    name: "PES TGM 6.0",
    photo: "/events/tgm.png",
    date: "2025",
    loc: "Tunisia",
    cat: "PES Chapter",
    col: "#00843d",
    desc: "The PES Tunisia General Meeting 6.0 centered on ENTREPOWER, exploring the intersection of entrepreneurship and the energy sector through challenges, ceremonies, and dynamic sessions.",
    url: "#",
  },
  {
    name: "Integration Day",
    photo: "/events/integraion.png",
    date: "Sep 1, 2025",
    loc: "ENIT, Tunis",
    cat: "Student Branch",
    col: "#005f99",
    desc: "ENIT's welcome day for over 200 new students, where IEEE ENIT SB introduced opportunities for learning, innovation, and personal growth through presentations and networking.",
    url: "#",
  },
  {
    name: "FUTURISE 20",
    photo: "/events/futurise.png",
    date: "2025",
    loc: "ENIT, Tunis",
    cat: "Student Branch",
    col: "#005f99",
    desc: "A full-day celebration marking IEEE ENIT SB's 20th anniversary, featuring leadership panels, the Tech4Good Challenge, a Young Professionals keynote, and a live violin performance.",
    url: "#",
  },
  {
    name: "WIE PROMPT 2.0",
    photo: "/events/wieprompt.png",
    date: "2025",
    loc: "Online",
    cat: "WIE Group",
    col: "#d63a8a",
    desc: "An online gathering co-hosted by 9 WIE affinity groups across Tunisia, dedicated to engaging women in cybersecurity and fostering connections among IEEE members nationwide.",
    url: "#",
  },
  {
    name: "20th Anniversary, Internal Celebration",
    photo: "/events/anniv.png",
    date: "2025",
    loc: "ENIT, Tunis",
    cat: "Student Branch",
    col: "#005f99",
    desc: "A team-building kickoff for the 20th anniversary celebrations, bringing officers and active members together through a cultural visit and outdoor games.",
    url: "#",
  },
  {
    name: "InSIGHTful Celebration",
    photo: "/events/sightday.png",
    date: "2025",
    loc: "Online",
    cat: "SIGHT Group",
    col: "#f97316",
    desc: "A webinar series honoring SIGHT Day with six global speakers covering humanitarian technology, UI/UX design, research writing, project management, and funding opportunities.",
    url: "#",
  },
  {
    name: "ENIT ROBOTS 6.0, The Maze Runner",
    photo: "/events/enitrobots.png",
    date: "2025",
    loc: "ENIT, Tunis",
    cat: "RAS Chapter",
    col: "#c0392b",
    desc: "A robotics competition for young innovators aged 8–16, organized by IEEE RAS ENIT. Participants designed and controlled robots to navigate mazes with speed and precision.",
    url: "#",
  },
  {
    name: "Media Bootcamp",
    photo: "/events/mediabootcamp.png",
    date: "2025",
    loc: "ENIT, Tunis",
    cat: "Student Branch",
    col: "#005f99",
    desc: "A hands-on training for new media officers in collaboration with IEEE ENSIT, covering graphic design fundamentals and tools like Photoshop and Illustrator.",
    url: "#",
  },
  {
    name: "GREENCON 3.0",
    photo: "/events/greencon.png",
    date: "2025",
    loc: "ENIT, Tunis",
    cat: "Student Branch",
    col: "#00843d",
    desc: "An ideathon focused on AI-driven solutions for sustainable post-war and disaster recovery. Teams collaborated under expert mentorship to design impactful rebuilding strategies.",
    url: "#",
  },
  {
    name: "Officers Team Building",
    photo: "/events/team-building.png",
    date: "2025",
    loc: "Tunisia",
    cat: "Student Branch",
    col: "#005f99",
    desc: "An immersive weekend retreat for IEEE ENIT SB officers, built around cooperative challenges, group exercises, and activities designed to strengthen leadership and teamwork.",
    url: "#",
  },
];

export const SUBS = [
  {
    abbr: "RAS SEN SBJC",
    name: "Robotics & Automation Society / Sensors Joint Chapter",
    logo: "/logos/ras sen white.png",
    col: "#ff3a5c",
    desc: "Advancing robotics, automation and sensor technologies through hands-on workshops, competitions and research projects that bridge smart systems with real-world engineering.",
  },
  {
    abbr: "CS SBC",
    name: "Computer Society Student Branch Chapter",
    logo: "/logos/CS White.png",
    col: "#f5c400",
    desc: "Promoting computing excellence through hackathons, coding challenges and technical workshops, a community for developers and innovators pushing the boundaries of software.",
  },
  {
    abbr: "IAS IES PES SBJC",
    name: "Industry Applications · Industrial Electronics · Power & Energy Joint Chapter",
    logo: "/logos/ias ies pes white.png",
    col: "#00c48c",
    desc: "A tri-society chapter tackling energy systems, industrial electronics and applied engineering, connecting students with industry through field visits and seminars.",
  },
  {
    abbr: "WIE SAG",
    name: "Women in Engineering Student Affinity Group",
    logo: "/logos/Wie-White.png",
    col: "#c850ff",
    desc: "Empowering women in STEM through mentorship programmes, leadership workshops and inspiring events that foster diversity and inclusion at ENIT.",
  },
  {
    abbr: "SIGHT Group",
    name: "Special Interest Group on Humanitarian Technology",
    logo: "/logos/sight white.png",
    col: "#f97316",
    desc: "Leveraging technology for social good through humanitarian initiatives, awareness campaigns and community-driven projects aligned with the UN's Sustainable Development Goals.",
  },
];

export const AWARDS_DATA = [
  {
    year: "2026",
    items: [
      { title: "Regional Exemplary Student Branch Award 2025", org: "IEEE Student", cat: "Excellence", col: "#FFD700" },
    ],
  },
  {
    year: "2025",
    items: [
      { title: "RAS Student Branch Chapter of the Year Award", org: "IEEE Robotics and Automation Society",        cat: "Chapter",    col: "#00bfff" },
      { title: "IEEE Student Branch SIGHT Group of the Year",  org: "IEEE HTB committee",      cat: "HTB", col: "#ff3a5c" },
      { title: "IEEE Sensors Council Outstanding Chapter Award", org: "IEEE Sensors Council", cat: "Chapter",  col: "#00c48c" },
      { title: "IEEE IAS CMD Outstanding Member Award",        org: "IEEE Student",      cat: "Excellence", col: "#FFD700" },
      { title: "Outstanding Student Branch Chapter Chair",     org: "IEEE Student",      cat: "Leadership", col: "#ff6b35" },
    ],
  },
  {
    year: "2024",
    items: [
      { title: "Regional Exemplary Student Branch Award 2023",   org: "IEEE Region 8",        cat: "Regional",   col: "#00bfff" },
      { title: "Regional Exemplary Student Branch Award 2024",   org: "IEEE Region 8",        cat: "Regional",   col: "#00bfff" },
      { title: "First Prize bIEEE Day Photo Contest 2024 (Raise Your Flag)", org: "IEEE Day", cat: "Activities", col: "#FFD700" },
      { title: "IEEE Outstanding Branch Counselor and Branch Chapter Advisor", org: "IEEE Student", cat: "Leadership", col: "#c850ff" },
    ],
  },
];

export const STARS = Array.from({ length: 180 }, (_, i) => ({
  id: i,
  x: Math.random() * 100,
  y: Math.random() * 100,
  r: Math.random() * 1.6 + 0.3,
  dur: (Math.random() * 4 + 2).toFixed(1),
  del: (Math.random() * 6).toFixed(1),
}));